version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: abc123
    ports:
      - '5432:5432'
    volumes:
      - pgdb:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - '8080:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
    pgdb:
      driver: local
    pgadmin:
      driver: local
